"""Tab 4/5/6/7: identity, dataset quality, badcase, and preview callbacks."""
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from latentsync.finetune import REPO_ROOT

def _ref_strategy_to_dataset_kwargs(strategy: str, min_distance: int) -> Dict[str, Any]:
    """Map UI strategy choice to UNetDataset-side kwargs.

    Currently UNetDataset only supports 'random' (the baseline). For
    'adjacent' and 'fixed_first_frame' we emit a code-side patch that the
    user can drop into latentsync/data/unet_dataset.py if they want.
    """
    if strategy == "random":
        return {
            "_strategy": "random",
            "ref_min_distance": min_distance,
            "_note": "Default UNetDataset.get_frames already picks random ref "
                     "outside the gt window. No code change needed.",
        }
    if strategy == "adjacent":
        return {
            "_strategy": "adjacent",
            "ref_min_distance": min_distance,
            "_patch": (
                "# In latentsync/data/unet_dataset.py:75-80, replace:\n"
                "while True:\n"
                "    ref_start_idx = random.randint(0, total_num_frames - self.num_frames)\n"
                "    if ref_start_idx > start_idx - self.num_frames and ref_start_idx < start_idx + self.num_frames:\n"
                "        continue\n"
                "# With:\n"
                "ref_start_idx = max(0, start_idx + self.num_frames + ref_min_distance)\n"
                "if ref_start_idx + self.num_frames > total_num_frames:\n"
                "    ref_start_idx = start_idx - self.num_frames - ref_min_distance\n"
            ),
        }
    # fixed_first_frame
    return {
        "_strategy": "fixed_first_frame",
        "ref_min_distance": 0,
        "_patch": (
            "# In latentsync/data/unet_dataset.py, replace ref sampling with:\n"
            "ref_start_idx = 0  # always use first frame as ref\n"
        ),
    }
def _dynamic_mask_mode_to_params(mode: str) -> Dict[str, float]:
    """Map UI mode to lipsync_pipeline.generate_dynamic_mouth_mask kwargs."""
    presets = {
        "conservative": {"pad_width_ratio": 1.2, "pad_height_top_ratio": 1.1,
                         "pad_height_bottom_ratio": 1.8, "feather_sigma_px": 5.0},
        "standard":     {"pad_width_ratio": 1.5, "pad_height_top_ratio": 1.3,
                         "pad_height_bottom_ratio": 2.2, "feather_sigma_px": 7.0},
        "aggressive":   {"pad_width_ratio": 2.0, "pad_height_top_ratio": 1.6,
                         "pad_height_bottom_ratio": 2.6, "feather_sigma_px": 10.0},
    }
    return presets[mode]
def generate_identity_kit(
    ref_strategy: str,
    ref_window_distance: int,
    dynamic_mask_mode: str,
    paste_back_blur_sigma: float,
    detail_strength: float,
    color_match_strength: float,
) -> str:
    """Build the kwargs dict the inference pipeline should receive, plus a
    yaml-style sidecar and human-readable warnings."""
    dataset_kwargs = _ref_strategy_to_dataset_kwargs(ref_strategy, ref_window_distance)
    mask_params = _dynamic_mask_mode_to_params(dynamic_mask_mode)
    mask_params["feather_sigma_px"] = float(paste_back_blur_sigma)

    inference_kwargs = {
        # L3: dynamic mask geometry
        "dynamic_mask_pad_width_ratio": mask_params["pad_width_ratio"],
        "dynamic_mask_pad_height_top_ratio": mask_params["pad_height_top_ratio"],
        "dynamic_mask_pad_height_bottom_ratio": mask_params["pad_height_bottom_ratio"],
        # L3: paste-back blur
        "paste_back_feather_sigma_px": mask_params["feather_sigma_px"],
        # L4: detail / color post-processing
        "mouth_detail_strength": float(detail_strength),
        "color_match_strength": float(color_match_strength),
    }

    lines: List[str] = []
    lines.append("# === LatentSync Identity-Protection Kit ===")
    lines.append("# Generated by gradio_finetune.py Tab 4")
    lines.append("")
    lines.append("# ----- 1) Python kwargs to pass to LipsyncPipeline.__call__ -----")
    lines.append("inference_kwargs = {")
    for k, v in inference_kwargs.items():
        lines.append(f"    {k!r}: {v!r},")
    lines.append("}")
    lines.append("# Usage:")
    lines.append("# pipe(video_path=..., audio_path=..., video_out_path=..., **inference_kwargs)")
    lines.append("")
    lines.append("# ----- 2) Dataset-side (UNetDataset) ref strategy -----")
    lines.append("# Strategy: " + dataset_kwargs["_strategy"])
    lines.append("# ref_min_distance: " + str(dataset_kwargs["ref_min_distance"]))
    if "_patch" in dataset_kwargs:
        lines.append("# Patch (drop into latentsync/data/unet_dataset.py:75-80):")
        for pl in dataset_kwargs["_patch"].splitlines():
            lines.append("#   " + pl)
    else:
        lines.append("# " + dataset_kwargs["_note"])
    lines.append("")
    lines.append("# ----- 3) Sanity warnings -----")
    if detail_strength > 0.85:
        lines.append("# ⚠️ detail_strength > 0.85 — generated mouth shape may be washed out.")
    if color_match_strength > 0.9:
        lines.append("# ⚠️ color_match_strength > 0.9 — over-correction may erase emotion.")
    if dynamic_mask_mode == "aggressive":
        lines.append("# ⚠️ aggressive mask + ref_min_distance small — identity drift possible.")
    if ref_strategy == "fixed_first_frame":
        lines.append("# ⚠️ fixed_first_frame reduces temporal diversity; expect lower sync_conf.")
    if paste_back_blur_sigma < 3.0:
        lines.append("# ⚠️ paste_back_blur < 3 px — visible seam at mask boundary.")
    return "\n".join(lines)
def reset_identity_defaults() -> Tuple[str, int, str, float, float, float]:
    return "random", 16, "standard", 7.0, 0.0, 0.0
def evaluate_dataset_quality(
    data_dir: str, max_videos: int
) -> Tuple[str, str, Any]:
    """Walk the directory, sample up to max_videos mp4s, compute HyperIQA +
    SyncNet confidence distributions, return summary text + issues + plot."""
    import statistics

    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    device = "cpu"
    if not data_dir or not Path(data_dir).exists():
        return (
            f"❌ 目录不存在: {data_dir}",
            "请检查路径。预期目录结构: data_dir/<speaker>/<video>.mp4 或 data_dir/*.mp4",
            None,
        )

    candidates = sorted(Path(data_dir).rglob("*.mp4"))[: int(max_videos)]
    if not candidates:
        return (f"❌ {data_dir} 下没有 .mp4 文件", "", None)

    hyperiqa_scores: List[float] = []
    sync_confs: List[float] = []
    broken: List[str] = []
    too_short: List[str] = []

    try:
        from eval.hyper_iqa import HyperNet, TargetNet
        from torchvision import transforms

        device = "cuda" if torch_available() else "cpu"
        model_hyper = HyperNet(16, 112, 224, 112, 56, 28, 14, 7).to(device)
        ckpt = REPO_ROOT / "checkpoints/auxiliary/koniq_pretrained.pkl"
        if ckpt.exists():
            model_hyper.load_state_dict(torch_load(str(ckpt), map_location=device))
            model_hyper.eval()
            hyperiqa_available = True
        else:
            hyperiqa_available = False
        tf = transforms.Compose([
            transforms.CenterCrop(224),
            transforms.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
        ])
    except Exception as e:
        hyperiqa_available = False
        tf = None
        print(f"[evaluate_dataset_quality] hyperiqa unavailable: {e}")

    syncnet_available = False
    try:
        from eval.syncnet import SyncNetEval
        from eval.syncnet_detect import SyncNetDetector
        from eval.eval_sync_conf import syncnet_eval as _sync_eval

        device = "cuda" if torch_available() else "cpu"
        if (REPO_ROOT / "checkpoints/auxiliary/syncnet_v2.model").exists():
            _se = SyncNetEval(device=device)
            _se.loadParameters("checkpoints/auxiliary/syncnet_v2.model")
            _sd = SyncNetDetector(device=device, detect_results_dir="detect_results")
            syncnet_available = True
    except Exception as e:
        print(f"[evaluate_dataset_quality] syncnet unavailable: {e}")

    for p in candidates:
        try:
            from decord import VideoReader
            vr = VideoReader(str(p))
            if len(vr) < 16:
                too_short.append(str(p))
                continue
            # sample first/middle/last frame
            idxs = [0, len(vr) // 2, len(vr) - 1]
            frames = vr.get_batch(idxs).asnumpy()
            frames_t = torch_from_numpy(_rearrange(frames, "f h w c -> f c h w")).float() / 255.0

            if hyperiqa_available and tf is not None:
                paras = model_hyper(tf(frames_t.clone()).to(device))
                model_target = TargetNet(paras).to(device)
                for p_ in model_target.parameters():
                    p_.requires_grad = False
                score = model_target(paras["target_in_vec"]).mean().item()
                hyperiqa_scores.append(score)

            if syncnet_available:
                # write frames as a tiny video? Easier: only eval if video has audio
                try:
                    _, conf = _sync_eval(_se, _sd, str(p), "temp")
                    if conf is not None:
                        sync_confs.append(conf)
                except Exception:
                    pass
        except Exception as e:
            broken.append(f"{p}: {e}")

    stats_lines = [
        f"📁 目录: {data_dir}",
        f"🎬 扫描视频数: {len(candidates)}",
        f"✅ 完整视频: {len(candidates) - len(broken) - len(too_short)}",
        f"❌ 损坏: {len(broken)}",
        f"⚠️ 太短 (<16 帧): {len(too_short)}",
    ]
    if hyperiqa_scores:
        stats_lines += [
            "",
            "📊 HyperIQA 分数（视觉质量，0-100）:",
            f"  mean: {statistics.mean(hyperiqa_scores):.2f}",
            f"  median: {statistics.median(hyperiqa_scores):.2f}",
            f"  min: {min(hyperiqa_scores):.2f}",
            f"  max: {max(hyperiqa_scores):.2f}",
            f"  ≥40 (preprocess 阈值): {sum(1 for s in hyperiqa_scores if s >= 40)} / {len(hyperiqa_scores)}",
        ]
    else:
        stats_lines.append("\n📊 HyperIQA 不可用（检查 checkpoints/auxiliary/koniq_pretrained.pkl）")
    if sync_confs:
        stats_lines += [
            "",
            "🎵 SyncNet confidence（音视同步）:",
            f"  mean: {statistics.mean(sync_confs):.2f}",
            f"  median: {statistics.median(sync_confs):.2f}",
            f"  min: {min(sync_confs):.2f}",
            f"  ≥3 (preprocess 阈值): {sum(1 for s in sync_confs if s >= 3)} / {len(sync_confs)}",
        ]
    else:
        stats_lines.append("\n🎵 SyncNet 不可用（检查 checkpoints/auxiliary/syncnet_v2.model）")

    issues: List[str] = []
    if broken:
        issues.append(f"❌ {len(broken)} 个损坏视频，建议先跑 remove_broken_videos")
        for b in broken[:5]:
            issues.append(f"   - {b}")
    if too_short:
        issues.append(f"⚠️ {len(too_short)} 个视频太短（<16 帧），训练时会被跳")
    if hyperiqa_scores and statistics.mean(hyperiqa_scores) < 40:
        issues.append("❌ 平均 HyperIQA < 40：数据质量整体偏低，建议重新跑 filter_visual_quality")
    if sync_confs and statistics.mean(sync_confs) < 3:
        issues.append("❌ 平均 SyncNet conf < 3：音视不同步，建议重新跑 sync_av")
    if not issues:
        issues.append("✅ 数据集看起来健康")

    # plot
    fig = None
    if hyperiqa_scores or sync_confs:
        fig, ax1 = plt.subplots(figsize=(7, 4))
        if hyperiqa_scores:
            ax1.hist(hyperiqa_scores, bins=20, alpha=0.6, label="HyperIQA", color="blue")
            ax1.axvline(40, color="blue", linestyle="--", label="HyperIQA ≥ 40")
            ax1.set_xlabel("HyperIQA score (0-100)")
        if sync_confs:
            ax2 = ax1.twinx()
            ax2.hist(sync_confs, bins=20, alpha=0.6, label="SyncNet conf", color="green")
            ax2.axvline(3, color="green", linestyle="--", label="SyncNet ≥ 3")
            ax2.set_xlabel("SyncNet confidence")
        fig.tight_layout()

    return ("\n".join(stats_lines), "\n".join(issues), fig)
def torch_available() -> bool:
    try:
        import torch
        return bool(torch.cuda.is_available())
    except Exception:
        return False
def torch_load(path: str, map_location: str = "cpu"):
    import torch
    return torch.load(path, map_location=map_location, weights_only=True)
def torch_from_numpy(arr):
    import torch
    return torch.from_numpy(arr)
def _rearrange(tensor, pattern):
    from einops import rearrange
    return rearrange(tensor, pattern)
_RECO_THRESHOLDS = {
    "identity_critical": 0.70,   # < 0.70 → face geometry distorted
    "identity_soft":    0.85,   # < 0.85 → suspicious, helps the multiplier
    "sync_critical":     5.0,    # < 5.0 → audio-visual sync weak
    "blurry_critical":   0.40,   # > 0.40 → 40%+ frames mouth-blurred
    "flicker_critical":  12.0,   # > 12 → temporal flicker severe
    "mouth_open_low":    0.18,   # p95 mouth openness < this → small mouth opening
}
def _recommend_finetune_preset(
    blurry: Optional[float], flicker: Optional[float],
    sync: Optional[float], identity: Optional[float],
    avg_yaw: Optional[float] = None,
    mouth_open: Optional[float] = None,
) -> str:
    """Return a multi-line recommendation string given the badcase metrics.

    Rules (in order):
      1. identity < 0.70                         → 🧩 Structural Fix
      2. avg_yaw ≥ 18° AND content issue         → 💋 Side-Face Lip Quality
         (overrides 🎯 Content Fix for heavy side-face content bugs)
      3. content issue AND identity 0.70-0.85    → 🧩 Structural Fix (cover both)
      4. content issue AND identity >= 0.85     → 🎯 Content Fix
      5. mouth_open < mouth_open_low (no content issue)
                                                 → 💋 Side-Face + big-mouth data
      6. identity 0.70-0.85 alone (no content)   → 🧩 Structural Fix (mild drift)
      7. all metrics OK                           → ⚪ no finetune needed
    """
    s = _RECO_THRESHOLDS
    parts = []
    if identity is not None:
        parts.append(f"id={identity:.3f}")
    if blurry is not None:
        parts.append(f"blurry={blurry*100:.0f}%")
    if flicker is not None:
        parts.append(f"flicker={flicker:.1f}")
    if sync is not None:
        parts.append(f"sync={sync:.2f}")
    if mouth_open is not None:
        parts.append(f"mouth_p95={mouth_open:.2f}")
    metric_summary = ", ".join(parts) if parts else "(no metrics yet)"

    if identity is not None and identity < s["identity_critical"]:
        return (
            "🧩 Structural Fix (LoRA + conv, 18-22GB)\n"
            f"   {metric_summary}\n"
            f"   身份保持 = {identity:.3f} < {s['identity_critical']:.2f} — "
            "脸几何/五官位置异常,须 wrap 卷积层才能修。"
        )
    has_content_issue = (
        (sync is not None and sync < s["sync_critical"])
        or (blurry is not None and blurry > s["blurry_critical"])
        or (flicker is not None and flicker > s["flicker_critical"])
    )
    structural_suspect = (
        identity is not None
        and s["identity_critical"] <= identity < s["identity_soft"]
    )

    # Rule 2 (BEFORE structural_suspect): side-face heavy + content issue
    # → 💋. This takes priority over the 0.70-0.85 identity range because
    # for side-face videos the shape is preserved but the lips are bad;
    # identity 0.82 on a side-face clip does NOT mean structural issue.
    if (
        avg_yaw is not None and avg_yaw >= 18.0
        and identity is not None and identity >= 0.70
        and has_content_issue
    ):
        return (
            "💋 Side-Face Lip Quality (LoRA+conv, 18-22GB)\n"
            f"   {metric_summary}\n"
            f"   平均 yaw = {avg_yaw:.1f}° ≥ 18° + 内容指标越界 → "
            "侧脸唇形专项(rank=48, sync=0.15, perceptual=0.25)。"
            "\n   数据:📚 预制 celebv_hq_head_talk_side (侧脸召回) / "
            "celebv_hq_head_talk_side_big_mouth (大嘴)。"
        )

    if has_content_issue:
        if structural_suspect:
            return (
                "🧩 Structural Fix (LoRA + conv, 18-22GB) — recommended (cover both)\n"
                f"   {metric_summary}\n"
                f"   内容型问题 + 身份保持 = {identity:.3f} 区间异常 → "
                "先攻结构,顺带 cover 内容。"
            )
        return (
            "🎯 Badcase Fix (LoRA, 12-15GB)\n"
            f"   {metric_summary}\n"
            f"   脸型 OK (id={identity:.3f}),内容指标越界 → att-only LoRA 就够。"
        )

    # has_content_issue is False from here. Now check small mouth, then
    # identity drift + side-face.
    small_mouth = mouth_open is not None and mouth_open < s["mouth_open_low"]
    if small_mouth:
        yaw_note = f"\n   平均 yaw = {avg_yaw:.1f}° — 侧脸场景," if (
            avg_yaw is not None and avg_yaw >= 18.0
        ) else "\n   "
        return (
            "💋 Side-Face Lip Quality (LoRA+conv, 18-22GB)\n"
            f"   {metric_summary}\n"
            f"   张嘴幅度 p95 = {mouth_open:.2f} < {s['mouth_open_low']:.2f} — "
            f"生成嘴张不开。{yaw_note}"
            "数据:📚 预制 celebv_hq_head_talk_side_big_mouth (p95≥0.22 大嘴筛选) "
            "是主要手段;preset sync_loss=0.15 强推 audio-driven 张嘴。"
        )

    if avg_yaw is not None and avg_yaw >= 18.0:
        return (
            "⚪ 当前侧脸场景内容指标正常,不需要 finetune。"
            f"\n   {metric_summary}\n"
            f"   平均 yaw = {avg_yaw:.1f}° ≥ 18° — 侧脸场景。"
            "如需主动加强侧脸唇形质量,可走 💋 Side-Face Lip Quality。"
        )

    if identity is not None and identity < s["identity_soft"]:
        return (
            "🧩 Structural Fix (LoRA + conv, 18-22GB)\n"
            f"   {metric_summary}\n"
            f"   内容型指标正常,但身份保持 = {identity:.3f} 偏低 → 脸轮廓漂,加 conv wrap。"
        )

    return (
        "⚪ 不需要 finetune / 用 Stage 2 LoRA baseline\n"
        f"   {metric_summary}\n"
        "   五个指标都在合理范围内。生成质量可用,需要换风格/换脸再调 preset。"
    )
def _diagnose_short_drama(
    video_path: str,
) -> str:
    """Quick offline heuristic for short-drama scene/speaker counts.

    Uses only cv2 + the existing face_detector (no new deps). Two
    signals:

      1. Shot count via HSV-histogram Bhattacharyya distance between
         sampled frames (>0.4 ⇒ cut).
      2. Speaker count via clustering of detected face-bbox centroids
         across frames (KMeans K in [1, 5]). Crude but works without
         face_recognition.

    Pure-python; runs in a few seconds on CPU.
    """
    import numpy as np
    import cv2
    if not video_path:
        return "❌ 请先上传视频"
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        return f"❌ 视频无法打开: {video_path}"
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    fps = cap.get(cv2.CAP_PROP_FPS) or 25.0
    if total < 30:
        cap.release()
        return f"❌ 视频太短 ({total} 帧)"

    # Sample frames evenly
    sample_n = min(64, max(20, total // 50))
    indices = np.linspace(0, total - 1, sample_n).astype(int)

    try:
        from latentsync.utils.face_detector import FaceDetector
        # Count side-face speakers too — the default 15° skip would drop them.
        detector = FaceDetector(device="cpu", skip_side_face_threshold=None)
    except Exception as exc:
        cap.release()
        return f"❌ face_detector 加载失败: {exc}"

    frames = []
    bboxes = []  # list of [cx, cy, w, h]
    yaws = []
    for idx in indices:
        cap.set(cv2.CAP_PROP_POS_FRAMES, int(idx))
        ok, frame = cap.read()
        if not ok or frame is None:
            continue
        frames.append(frame)
        bbox, _ = detector(frame)
        if bbox is not None:
            x1, y1, x2, y2 = [int(v) for v in bbox]
            cx, cy = (x1 + x2) / 2.0, (y1 + y2) / 2.0
            bboxes.append([cx / frame.shape[1], cy / frame.shape[0],
                           (x2 - x1) / frame.shape[1], (y2 - y1) / frame.shape[0]])
            if detector.last_pose_yaw is not None:
                yaws.append(float(detector.last_pose_yaw))
    cap.release()

    # ---- shot count ----
    shots = 1
    for i in range(1, len(frames)):
        a = cv2.cvtColor(frames[i - 1], cv2.COLOR_BGR2HSV)
        b = cv2.cvtColor(frames[i], cv2.COLOR_BGR2HSV)
        ha = cv2.calcHist([a], [0, 1], None, [8, 8], [0, 180, 0, 256])
        hb = cv2.calcHist([b], [0, 1], None, [8, 8], [0, 180, 0, 256])
        cv2.normalize(ha, ha); cv2.normalize(hb, hb)
        if cv2.compareHist(ha, hb, cv2.HISTCMP_BHATTACHARYYA) > 0.4:
            shots += 1

    # ---- speaker count via greedy centroid clustering ----
    speaker_count = 1
    centroids: list = []
    for bb in bboxes:
        cx, cy, w, h = bb
        placed = False
        for c in centroids:
            if (abs(cx - c[0]) < 0.18 and abs(cy - c[1]) < 0.18
                    and abs(w - c[2]) < 0.15 and abs(h - c[3]) < 0.15):
                placed = True
                break
        if not placed:
            centroids.append([cx, cy, w, h])
            speaker_count += 1
        if speaker_count >= 5:
            break

    # ---- summary text ----
    avg_yaw = float(np.mean(np.abs(yaws))) if yaws else 0.0
    duration_s = total / fps
    print_lines = [
        "🎬 短剧场景诊断",
        f"   时长:           {duration_s:.1f}s  ({total} 帧 @ {fps:.1f}fps)",
        f"   估计场景数:     {shots}",
        f"   估计说话人数:   {speaker_count}",
        f"   平均 yaw:       {avg_yaw:.1f}°",
        f"   检出 face 帧:   {len(bboxes)} / {len(frames)}",
        "",
    ]
    if speaker_count >= 2 or shots >= 3:
        print_lines.extend([
            "📋 推荐路径:",
            "   数据:python tools/preprocess_short_drama.py --input <video> ...",
            "   训练:Tab 1 preset 选 '🎬 Short Drama (LoRA+conv, 多说话人, 18-22GB)'",
            "   数据集:先 preprocess_short_drama 切场景,再 curate_finetune_samples 分桶",
        ])
    elif speaker_count == 1 and shots <= 2:
        print_lines.append("📋 这条看起来是单场景单人,常规 🎯 Badcase Fix 就够。")
    return "\n".join(print_lines)
_IDENTITY_APP = None


def _face_embedding(frame):
    """Largest-face embedding via insightface recognition (lazy singleton).

    The shared ``FaceDetector`` only loads detection + landmarks and never
    exposes embeddings, so Tab 6 keeps its own FaceAnalysis instance with
    the recognition module instead of touching the pipeline-shared class.
    """
    global _IDENTITY_APP
    from insightface.app import FaceAnalysis

    if _IDENTITY_APP is None:
        app = FaceAnalysis(
            allowed_modules=["detection", "recognition"],
            root="checkpoints/auxiliary",
            providers=["CUDAExecutionProvider"],
        )
        app.prepare(ctx_id=0, det_size=(512, 512))
        _IDENTITY_APP = app

    faces = _IDENTITY_APP.get(frame)
    if not faces:
        return None
    faces.sort(
        key=lambda f: float((f.bbox[2] - f.bbox[0]) * (f.bbox[3] - f.bbox[1])),
        reverse=True,
    )
    emb = getattr(faces[0], "normed_embedding", None)
    if emb is None:
        emb = getattr(faces[0], "embedding", None)
    return emb


def run_badcase_checklist(
    video_path: str, reference_video_path: Optional[str]
) -> Tuple[float, float, float, float, float, float, str]:
    """Run all badcase checks on a single generated video.

    Returns (blurry_ratio, flicker_score, sync_conf, identity_sim,
    avg_yaw, mouth_open_p95, report). avg_yaw is the mean |yaw| in
    degrees across detected-face frames; mouth_open_p95 is the 95th
    percentile mouth height/width ratio. Both feed
    _recommend_finetune_preset (side-face + small-mouth badcases).
    """
    if not video_path:
        return 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, "❌ 请先上传视频"

    try:
        from decord import VideoReader
        import numpy as np
        import cv2
        vr = VideoReader(video_path)
        total = len(vr)
        if total < 2:
            return 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, "❌ 视频帧数 < 2"
        # Bound memory on long inputs: blur/flicker run on a contiguous
        # middle window (contiguous so the flicker diff stays meaningful);
        # identity / yaw / mouth openness sample the full video below.
        max_frames = 400
        win_start = max(0, (total - max_frames) // 2)
        frames = [f.asnumpy() for f in vr[win_start:min(total, win_start + max_frames)]]
        if len(frames) < 2:
            return 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, "❌ 视频帧数 < 2"

        # ---- 1. Blurry mouth ratio ----
        # crude: convert to grayscale, Laplacian variance per frame
        grays = [cv2.cvtColor(f, cv2.COLOR_RGB2GRAY) for f in frames]
        laps = [cv2.Laplacian(g, cv2.CV_64F).var() for g in grays]
        blurry_count = sum(1 for v in laps if v < 50)
        blurry_ratio = blurry_count / len(laps)

        # ---- 2. Flicker score ----
        # mean abs difference between consecutive frames
        diffs = []
        for i in range(1, len(frames)):
            d = np.abs(frames[i].astype(float) - frames[i - 1].astype(float)).mean()
            diffs.append(d)
        flicker_score = float(np.mean(diffs))

        # ---- 3. SyncNet confidence ----
        sync_conf = 0.0
        try:
            from eval.syncnet import SyncNetEval
            from eval.syncnet_detect import SyncNetDetector
            from eval.eval_sync_conf import syncnet_eval as _sync_eval

            device = "cuda" if torch_available() else "cpu"
            if (REPO_ROOT / "checkpoints/auxiliary/syncnet_v2.model").exists():
                _se = SyncNetEval(device=device)
                _se.loadParameters("checkpoints/auxiliary/syncnet_v2.model")
                _sd = SyncNetDetector(device=device, detect_results_dir="detect_results")
                _, sync_conf = _sync_eval(_se, _sd, video_path, "temp")
        except Exception as e:
            sync_conf_note = f"SyncNet 评估失败: {e}"
        else:
            sync_conf_note = None

        # ---- 4. Identity similarity (only if reference provided) ----
        identity_sim = 0.0
        identity_sim_note = None
        if reference_video_path:
            try:
                ref_frame = VideoReader(reference_video_path)[0].asnumpy()
                gen_frame = vr[0].asnumpy()
                real_emb = _face_embedding(ref_frame)
                gen_emb = _face_embedding(gen_frame)
                if real_emb is None or gen_emb is None:
                    identity_sim_note = "identity 评估: 参考或生成视频首帧未检测到人脸"
                else:
                    real_emb = np.asarray(real_emb, dtype=float)
                    gen_emb = np.asarray(gen_emb, dtype=float)
                    denom = float(np.linalg.norm(real_emb) * np.linalg.norm(gen_emb))
                    if denom > 0:
                        identity_sim = float(np.dot(real_emb, gen_emb) / denom)
            except Exception as e:
                identity_sim_note = f"identity 评估失败: {e}"

        # ---- 5. Average yaw + mouth openness (sampled face detection) ----
        # Sample up to 16 frames evenly across the FULL video; run
        # face_detector; record |yaw| and mouth openness (lip height /
        # width, same landmarks as curation). Lightweight — face_detector
        # runs in <1s for 16 frames.
        mouth_open_p95 = 0.0
        try:
            from latentsync.utils.face_detector import FaceDetector
            # No side-face skip: side frames must count for yaw + mouth stats.
            _fd = FaceDetector(skip_side_face_threshold=None)
            sample_n = min(16, total)
            sample_idx = np.linspace(0, total - 1, sample_n).astype(int)
            yaws = []
            mouth_opens = []
            for idx in sample_idx:
                _, lmk = _fd(vr[int(idx)].asnumpy())
                if _fd.last_pose_yaw is not None:
                    yaws.append(abs(float(_fd.last_pose_yaw)))
                if lmk is not None and len(lmk) >= 106:
                    try:
                        mh = float(np.linalg.norm(lmk[57] - lmk[51]))
                        mw = float(np.linalg.norm(lmk[54] - lmk[48]))
                        if mw > 1e-3:
                            mouth_opens.append(mh / mw)
                    except (IndexError, TypeError, ValueError):
                        pass
            avg_yaw = float(np.mean(yaws)) if yaws else 0.0
            if mouth_opens:
                mouth_open_p95 = float(np.percentile(mouth_opens, 95))
        except Exception:
            avg_yaw = 0.0

        # ---- Build report ----
        lines: List[str] = []
        lines.append(f"📊 视频: {video_path}")
        lines.append(f"📏 总帧数: {total}")
        lines.append(f"🔍 Laplacian sharpness 范围: {min(laps):.1f} ~ {max(laps):.1f}")
        lines.append("")
        if blurry_ratio < 0.30:
            lines.append(f"✅ 嘴糊比例 {blurry_ratio:.1%} < 30% (目标)")
        else:
            lines.append(f"⚠️ 嘴糊比例 {blurry_ratio:.1%} ≥ 30%")
            lines.append("   建议: 升 512 分辨率 / 加 LPIPS weight / 开 CodeFormer")
        lines.append("")
        if flicker_score < 8:
            lines.append(f"✅ 闪烁评分 {flicker_score:.2f} < 8 (目标)")
        else:
            lines.append(f"⚠️ 闪烁评分 {flicker_score:.2f} ≥ 8")
            lines.append("   建议: 恢复 TREPA=10 / Motion Module 训够 / 开时序稳定")
        lines.append("")
        if sync_conf > 7:
            lines.append(f"✅ 唇音同步 {sync_conf:.2f} > 7 (目标)")
        elif sync_conf > 4:
            lines.append(f"⚠️ 唇音同步 {sync_conf:.2f} (4-7 中等)")
            lines.append("   建议: 重训 SyncNet (batch≥1024) / 加大 sync_loss_weight")
        else:
            lines.append(f"❌ 唇音同步 {sync_conf:.2f} < 4 (差)")
            lines.append("   建议: 大概率 SyncNet 没训稳，回去查 5 因素")
        lines.append("")
        if reference_video_path:
            if identity_sim > 0.8:
                lines.append(f"✅ 身份保持 {identity_sim:.3f} > 0.8 (目标)")
            elif identity_sim > 0.6:
                lines.append(f"⚠️ 身份保持 {identity_sim:.3f} (0.6-0.8 中等)")
                lines.append("   建议: 检查 UNetDataset ref 窗口选择 / 调 identity_similarity 阈值")
            else:
                lines.append(f"❌ 身份保持 {identity_sim:.3f} < 0.6 (差)")
                lines.append("   建议: identity 严重丢失，检查 paste_surrounding_pixels_back 是否生效")
        else:
            lines.append("ℹ️ 未提供参考视频，跳过 identity sim 检查")
        if sync_conf_note:
            lines.append(f"\n⚠️ {sync_conf_note}")
        if identity_sim_note:
            lines.append(f"⚠️ {identity_sim_note}")
        # yaw summary
        if avg_yaw > 0:
            if avg_yaw >= 25:
                lines.append("")
                lines.append(f"⚠️ 平均 yaw {avg_yaw:.1f}° ≥ 25° — 偏侧脸场景")
                lines.append("   建议: Tab 1 preset 选 💋 Side-Face Lip Quality "
                             "(sync_loss↑ perceptual↑ conv wrap)")
            elif avg_yaw >= 15:
                lines.append("")
                lines.append(f"ℹ️ 平均 yaw {avg_yaw:.1f}° (15-25° 区间) — 轻度侧脸")
                lines.append("   若同步/清晰度不佳,可考虑 💋 Side-Face Lip Quality")
            else:
                lines.append(f"\n✅ 平均 yaw {avg_yaw:.1f}° < 15° (基本正面)")
        # mouth openness summary
        if mouth_open_p95 > 0:
            if mouth_open_p95 < _RECO_THRESHOLDS["mouth_open_low"]:
                lines.append("")
                lines.append(f"⚠️ 张嘴幅度 p95 {mouth_open_p95:.2f} < {_RECO_THRESHOLDS['mouth_open_low']:.2f} — 嘴张不开")
                lines.append("   建议: 用 📚 celebv_hq_head_talk_side_big_mouth (p95≥0.22 大嘴) 数据重训, "
                             "preset 选 💋 Side-Face Lip Quality (sync_loss=0.15)")
            else:
                lines.append(f"\n✅ 张嘴幅度 p95 {mouth_open_p95:.2f} ≥ {_RECO_THRESHOLDS['mouth_open_low']:.2f} (正常)")

        return blurry_ratio, flicker_score, float(sync_conf), identity_sim, avg_yaw, mouth_open_p95, "\n".join(lines)
    except Exception as e:
        return 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, f"❌ 检测失败: {e}"
